---
- hosts: all
  tasks:
    - name: test for firt time
      ping:
    - name: update
      yum: name=* state=latest update_cache=yes
    - name: install firefox
      yum: name=firefox state=latest

      
- hosts: all
  roles:
    - { role: motd }